### ISSUE TITLE
Player ID issues

### ISSUE THREAD

**Issue by IF-Adin** [beyond-all-reason/BYAR-Chobby#39]
There should be an easy way to both see and change the player ID. Right now you can only force it via the console, but for new players this is a tall ask.

**Comment by gajop** [comment]
What is the player ID? I think you're in the wrong repo

**Comment by Ruwetuin** [comment]
he means teamid

**Comment by gajop** [comment]
Spring engine's teamID? The thing that'd allow you to coop with other people?

**Comment by Damgam** [comment]
Yes. When Autobalance is off Chobby is setting everyone's teamID to 1 which causes a lot of trouble.

**Comment by gajop** [comment]
I see. I think Chobby should be changed to pick a unique teamID.

I don't think I want to introduce the "teamID" option picker since it's very unintuitive (bad naming, advanced option you don't want visible most of the time)

**Comment by PtaQQ** [comment]
+1 to gajop, its causing confusion way too often. Making sure chobby chose free id is wiser, though it would be nice to have some visible way to show if you are in coop with someone if such thing is desired by players.

**Comment by gajop** [comment]
honestly I dislike how uberserver does coop since it can be forced upon you by other players; you should be able to choose if you want to coop with others.. it should be some sort of invite
.. but i'll leave that for later as it should involve some infra work; for now just picking the unique team ID should be enough
