### ISSUE TITLE
All tooltips disappear occasionally

### ISSUE THREAD

**Issue by salinecitrine** [beyond-all-reason/BYAR-Chobby#495]
Here's what appears to be the relevant portion of my infolog:

```
[t=01:36:03.970999][f=0052994] [LuaMenu] Error: In Update(): [string "LuaMenu/Widgets/gui_tooltip.lua"]:251: attempt to perform arithmetic on upvalue 'recentSpadsRequestSent' (a nil value)
[t=01:36:03.971053][f=0052994] [LuaMenu] Error: Removed widget: <Cursor tooltip>
```

And [here](https://github.com/beyond-all-reason/BYAR-Chobby/blob/9149ea08092c152f9cadf55c18ab5dca6fc1c334/LuaMenu/widgets/gui_tooltip.lua#L251) is the relevant line in `gui_tooltip.lua`.

I only noticed this happening recently. Maybe it was introduced in 58d5ed0d9e3eeb21b4f10ab18230229c8dea26bd ? I'm not very familiar with the code though, so it's hard for me to tell.

The only workaround, as far as I know, is restarting BAR (is there a way to reload chobby widgets?).

@FIr3baL since it looks like you were the last to look at this file.

**Comment by FIr3baL** [comment]
Thanks for this one a lot.

I noticed this one already and it's on my pipeline.
Though, i hope it's not that big of a deal since it's not that often and you only run into the problem when looking into battle tooltips while searching for your next lobby. So, you can restart at this point without necessary loose any queue pos etc.

It's addressed and i'll look into it once some other main topics done !

**Comment by FIr3baL** [comment]
Should be solved by https://github.com/beyond-all-reason/BYAR-Chobby/pull/509
