### ISSUE TITLE
the launcher has an electron icon

### ISSUE THREAD

**Issue by Ruwetuin** [beyond-all-reason/BYAR-Chobby#5]
after you launch the launcher, the taskbar does have the bar icon, i just mean the shortcut icon for the launcher itself

**Comment by gajop** [comment]
I can confirm this issue can now be closed by https://github.com/beyond-all-reason/BYAR-Chobby/commit/2053880f6e2ecb9425c9f023691a7cfb6b49edc2 .
The BYAR icon should probably be updated to a real 256x256 instead of an upscaled one, but other than that, it seems to work.

I've noticed Windows 10 doesn't react immediately when shortcut icons change (not even after deleting and recreating them). Your users may need to do delete the shortcut and do a system restart for this to take effect (restart was definitely necessary).
